spring:
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
        format_sql: true
  sql:
    init:
      mode: always
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/ewm-events
    username: root
    password: root

logging:
  level:
    org.springframework.orm.jpa: info
    org.springframework.transaction: info
    org.springframework.transaction.interceptor: trace
    org.springframework.orm.jpa.JpaTransactionManager: debug

service:
  name: events-service

server:
  port: 0
